### ISSUE TITLE
Clan System ToDO list

### ISSUE THREAD

**Issue by ChewyAurora** [DrHenny/668-Issues#37]
Finished:

- [x] Creating
- [x] Clan Flag (vex) / Cape (Selecting colours and emblem) <-- took a long time to figure it out ngl
- [x] Auto join on login
- [x] Leave on logout
- [x] Talking
- [x] Saving / Loading
- [x] Majority widget buttons

TODO:

- [ ] Inviting
- [ ] Kicking
- [ ] Disbanding
- [ ] Motto editing
- [ ] Keyword editing
- [ ] Clan data widget
- [ ] Assigning jobs
- [ ] Selecting Flag
